language: android

jdk:
- oraclejdk8

dist: trusty

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-30.0.3
  - android-30
  - sys-img-armeabi-v7a-android-30

notifications:
  email: false

before_script:
- chmod +x ./gradlew

script:
- ./gradlew clean
- ./gradlew build
- ./gradlew test