language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - sys-img-armeabi-v7a-android-28

notifications:
  email: false

before_script:
- chmod +x ./gradlew

script:
- ./gradlew clean
- ./gradlew build
- ./gradlew test